name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'ClassLibrary.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'